FROM python:3.11

# Builds with conexts ../
COPY ./acl_imdb/app /app/
RUN pip3 install -r /app/requirements.txt

# Install SDK
RUN --mount=type=bind,source=./ml_sdk,target=/tmp/ml_sdk,rw\
    pip3 install 'file:///tmp/ml_sdk#egg=ml_sdk'

WORKDIR /app

CMD ["python", "service.py", "-m", "Serve"]
